<?php
# no_calext.php
#
# This file defines additional special days for use in the calendar.
#
# The format is sort of funky at the moment, so adding your own entries might be a bit of a hassle.
# You need to add each entry to the array (you need to be familiar with the syntax for that) as shown.
# The entries starting and ending with # are the ones you need to fill in, the rest need to be literal as shown.
#
# Popup-box with description:
# gregoriantojd(#MONTH#,#DAY#,$year)=>"<a onClick=\"javascript:return overlib('#DESCRIPTION#', CAPTION, '#TITLE#');\">#TITLE#</a>",
#
# No popup, just a calendar entry:
# gregoriantojd(#MONTH#,#DAY#,$year)=>"#TITLE#",
#
# The file needs to be named 3-letter-language_calext.php
# Examples:
# ger_calext.php (german)
# swe_calext.php (swedish)
# dan_calext.php (danish)
# ...etc. It has to match the abbreviation used in the language file.
#
# Some later version of AKKAR might use a parseable fileformat (like an ini-file) or a database table instead, but for now this 
# is it. As it's mostly for fun and not really too usefull, making it more configurable is sort of low on the priority-list - the
# only reason it's here in the first place is just because I went overboard when I first made the calendar, figured I might as well
# go all the way ;)
#

# Holidays live in this array.
$helligdager = array(
	gregoriantojd(5,1,$year)=>"Arbeiderdagen",
	gregoriantojd(5,8,$year)=>"Frigjøringsdag",
	gregoriantojd(5,17,$year)=>"Nasjonaldag",
);

# Other traditional and special days go into this array.
$merkedager = array(
	gregoriantojd(1,1,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var primstavtegnet et solhjul, et timeglass eller en kirke. Dette var en viktig dag for å spå vær og avling for det kommende året.', CAPTION, 'Åttende dag jul');\">Åttende dag jul</a>",
	gregoriantojd(1,5,$year)=>"<a onClick=\"javascript:return overlib('Etter no. folketrad. skulle det ikke arbeides på denne dagen.', CAPTION, 'Trettendeaften, Tolvtedag jul');\">Trettendeaften</a>",
	gregoriantojd(1,6,$year)=>"<a onClick=\"javascript:return overlib('Ble feiret til minne om de tre vise menn som kom til Betlehem. I no. folketrad. var primstavtegnet tre kors, kroner eller menn. Dagen var en viktig merkedag for vær og avling. Dette var også dagen da man reiste hjem etter julefeiringen.', CAPTION, 'Hellig tre kongers dag, Trettendedag jul');\">Hellig tre kongers dag</a>",
	gregoriantojd(1,7,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. skålte man for åreilden denne dagen, antakelig for å berge husvarmen gjennom vinteren. Primstavmerket var et kors; dagen ble også kalt St. Knut til minne om den da. hertug Knud Erikssøn Lavard.', CAPTION, 'Eldbjørgdag <em>eg. \'ildbergingsdag\'</em>');\">Eldbjørgdag</a>",
	gregoriantojd(1,11,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var primstavmerket en øks eller en hest. Denne dagen ville ting brekke lett, bl.a. skulle man la hesten hvile, ellers kunne den brekke et bein.', CAPTION, 'Brettemesse, brokkis-/brykkesmesse <em>(av ukj. opphav)</em>');\">Brettemesse</a>",
	gregoriantojd(1,12,$year)=>"<a onClick=\"javascript:return overlib('Halvveis mellom første vinterdag og første sommerdag. I no. folketrad. var primstavmerket gjerne prikker som skulle symbolisere snø. M. var en hedensk fest, og i førkristen tid feiret man juleblot denne dagen.', CAPTION, 'Midtvinterdag');\">Midtvinterdag</a>",
	gregoriantojd(1,13,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var primstavmerket en øks, til minne om mordet på den da. hertug Knut Lavard. Andre merker var klokke, tønne eller omvendt drikkehorn. Dagen markerte slutten på julefeiringen.', CAPTION, 'Tyvendedag jul, Knutsdag');\">Tyvendedag jul</a>",
	gregoriantojd(1,17,$year)=>"<a onClick=\"javascript:return overlib('Til minne om eremitten Antonius som ble fristet og angrepet av Djevelen. I no. folketrad. var primstavmerket et kors eller en gris, siden St. Antonius var husdyrenes skytshelgen.', CAPTION, 'Antonsmesse');\">Antonsmesse</a>",
	gregoriantojd(1,20,$year)=>"<a onClick=\"javascript:return overlib('Til minne om helgenene Fabian og Sebastian som ble drept med hhv. øks og piler. I no. folketrad. var primstavmerket en øks eller to piler i kors. Emneveden måtte hugges denne dagen før sevjen steg.', CAPTION, 'Brødremesse');\">Brødremesse</a>",
	gregoriantojd(1,22,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for Vincentius fra Saragossa som led martyrdøden år 304. I no. folketrad. het det at solskinn på denne dagen ville gi et godt år.', CAPTION, 'Vincentius');\">Vincentius</a>",
	gregoriantojd(1,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen Paulus\' omvendelse. I no. folketrad. var primstavtegnet en bue, et sverd eller en fisk. Dagen kunne gi varsler om vær eller årsvekst, og man skulle helst ikke arbeide denne dagen.', CAPTION, 'Pålsmesse, Pål med bogen, Pål skytter');\">Pålsmesse</a>",
	gregoriantojd(2,2,$year)=>"<a onClick=\"javascript:return overlib('I katolsk tid vigslet man lysene denne dagen. I no. folketrad. var primstavmerket ofte en syvarmet lysestake, en lilje eller et kronet hode.', CAPTION, 'Kyndelsmesse, Kindermesse, Kjærmesse <em>(av lat. missa candelarum; lysenes messe)</em>');\">Kyndelsmesse</a>",
	gregoriantojd(2,3,$year)=>"<a onClick=\"javascript:return overlib('Til minne om biskop Blasius fra Armenia som døde som martyr i 316. I Norden ble navnet tolket som blest; hvis det blåste på denne dagen, ville det bli mye vind året igjennom. Derfor viste primstavmerket ofte et horn eller et skip for fulle seil.', CAPTION, 'Blåsmesse, Blåsius');\">Blåsmesse</a>",
	gregoriantojd(2,5,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den hellige Agatha fra Sicilia, som ble levende brent i 251. I kat. land er hun skytshelgen mot brann. I no. folketrad. het det at musene gnagde ørene og nesen av henne, inntil hun lovte å holde dagen hellig. Primstavmerket var ofte en mus eller et kors.', CAPTION, 'Ågotsmesse, Musedagen');\">Ågotsmesse</a>",
	gregoriantojd(2,6,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for den hellige Dorotea som led martyrdøden i år 304. Kjent i sv. og da. folketradisjon.', CAPTION, 'Dortemesse');\">Dortemesse</a>",
	gregoriantojd(2,9,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for Appollonia som led martyrdøden i år 249. Hun fikk slått ut alle tennene, og ble derfor anropt denne dagen av folk med tannpine. Hun er også tannlegenes \'skytshelgen\'.', CAPTION, 'Appollonia');\">Apollonia</a>",
	gregoriantojd(2,14,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for presten Valentin som skal ha helbredet en blind pike. I folketradisjonen var dette en fest for våren og fruktbarheten, og for unge elskende. Dagen symboliseres med et hjerte, og feires fortsatt, særlig i engelsktalende land. I de senere år har skikken med å sende såkalte valentinkort også kommet til Norge.', CAPTION, 'St. Valentins dag');\">St. Valentinsdag</a>",
	gregoriantojd(2,22,$year)=>"<a onClick=\"javascript:return overlib('Apostelen Peter; stifteren av pavestolen, ble gjort til den kat. kirkens overhode denne dagen. I no. folketrad ble dagen ofte kalt Per varmestein eller Per heitstein (fordi St. Peter kastet varme stener i vannet denne dagen slik at telen kunne gå opp). Regnet som første vårdag mange steder. Primstavmerket var en nøkkel (pavens tegn) eller en sten.', CAPTION, 'Peters stol <em>(av. lat. Cathedra Petri apostoli)</em>');\">Peters stol</a>",
	gregoriantojd(2,24,$year)=>"<a onClick=\"javascript:return overlib('St. Matthias ble apostel etter Judas Iskariot, og ble iflg. tradisjonen halshugget. Primstavmerket kunne derfor være en \'M\' (ofte omvendt) eller en øks.', CAPTION, 'Mattismesse vår, Mattis');\">Mattismesse vår</a>",
	gregoriantojd(3,8,$year)=>"<a onClick=\"javascript:return overlib('Dagen er satt til å markere diskriminering av kvinner. Markeringen startet i 1910, på Den annen internasjonales sosialistiske kvinnekongress i København. I 1975 bestemte FN at 8. mars skulle bli den internasjonale kvinnedagen, men både før og etter 1975 har kvinner og menn kjempet for at kvinner i alle land skal få det bedre.', CAPTION, 'Kvinnedagen');\">Kvinnedagen</a>",
	gregoriantojd(3,9,$year)=>"<a onClick=\"javascript:return overlib('Til minne om 40 romerske soldater som ble drept i Armenia på 300-tallet. I no. folketrad. er dagen av og til merket på primstaven, da med en halv sol. Som været var denne dagen skulle det være de følgende 40 dagene.', CAPTION, 'De førti riddere');\">De førti riddere</a>",
	gregoriantojd(3,12,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var dette en viktig merkedag; hvis det var sønnavind og dryppet fra takene, ville det bli et godt år. I no. byer var det skikk at barna, særlig jentene, gikk \'gregoriusbrud\', utkledte for å be om almisser. Det var også lov til å narre hverandre på denne dagen. Primstavmerket viser en fugl; en av Gregorius\' attributter var en due.', CAPTION, 'Gregormesse, Gregoriusdagen, Gregus-/Groårsmesse');\">Gregormesse</a>",
	gregoriantojd(3,16,$year)=>"<a onClick=\"javascript:return overlib('For den isl. biskop Gudmund den gode. I no. folketrad. er dagen kjent på øvre Romerike og Solør, antagelig pga. en bygdehelgen med samme navn på Romerike.', CAPTION, 'Gudmundsdagen');\">Gudmundsdagen</a>",
	gregoriantojd(3,17,$year)=>"<a onClick=\"javascript:return overlib('Til minne om abedissen Gertrude av Nivelles, skytshelgen for spinnerskene. I no. folketrad. var primstavmerket gjerne en rokkesnelle eller lilje. Det het seg at det ofte var uvær denne dagen, og skrikene til svartspetten (\'gjertrudsfuglen\') ga dårlige varsler.', CAPTION, 'Gjertrudsmesse, Gjertrudsdagen');\">Gjertrudsmesse</a>",
	gregoriantojd(3,18,$year)=>"<a onClick=\"javascript:return overlib('Etter dominikaneren Peter fra Verona som ble drept av katarene og senere kanonisert. Hans attributt er en dolk. I no. folketrad. er primstavmerket en pigghakke, siden Per ville prøve isen med en slik hakke denne dagen.', CAPTION, 'Petrus martyr, Per pekk i vatn');\">Petrus martyr</a>",
	gregoriantojd(3,21,$year)=>"<a onClick=\"javascript:return overlib('Til minne om stifteren av benediktinerordenen, Benedict av Nursia. I no. folketrad. var dette dagen for å slippe grisen ut. Primstavtegnet var et halvt kors, ofte tolket som en hakke. Dette skulle bety at våronna sto for døren. Også kalt jamvår, siden dagen og natten nå er like lange.', CAPTION, 'Bendiksmesse, Bendik/Bent prøvesvin');\">Bendiksmesse</a>",
	gregoriantojd(3,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om engelen Gabriels besøk hos Maria, der han bebudet Kristi fødsel. I no. folketrad. var primstavmerket krone, kvinnefigur, hode eller tre. Dette skulle være en gunstig dag å plante trær på, og dagene rundt ga viktige merker for været.', CAPTION, 'Vårfrumesse, Marimesse, vårmesse, Maria bebudelsesdag');\">Vårfrumesse</a>",
	gregoriantojd(2,29,$year)=>"<a onClick=\"javascript:return overlib('Navnet skuddår kommer av at det ble \'skutt\' inn en ekstra dag, men fra gammelt av ble dette gjort mellom den 23. og 24. februar. Mattismesse, som de øvrige årene var lagt til den 23.februar, ble i skuddår lagt til den 24.2. Mattismesse blir derfor også kalt laupårsmesse, av skuddår = laupår.<br><br>Det er ikke knyttet folkelig tradisjon til skuddårsdagen i Norge, og dette gjelder også det øvrige Norden. Troels-Lund nevner den ikke i det hele tatt i sin store beskrivelse av dagliglivet i Norden i det 16. århundre. Markering av skudd-årsdagen er heller ikke nevnt i Salmonsens leksikon eller i senere oversikter over årets festdager i Norden.', CAPTION, 'Skuddårsdag');\">Skuddårsdag</a>",
	gregoriantojd(4,1,$year)=>"<a onClick=\"javascript:return overlib('Over store deler av verden er det skikk å narre hverandre denne dagen. I India er dette er betraktet som en eldgammel skikk, og kan være brakt til Europa herfra. Kjent også i gamle Rom. Djevelen skulle ha fritt spillerom denne dagen, men han kunne la seg narre. Kjent i Norden og Tyskland fra midten av 1600-tallet.', CAPTION, 'Narredagen');\">Narredagen</a>",
	gregoriantojd(4,14,$year)=>"<a onClick=\"javascript:return overlib('I no. trad. en førkristen fest som markerer vinterens slutt. Primstaven ble snudd til sommersiden, og merket for dagen var oftest løvtre eller -grein. Dagen ga viktige varsler for hvordan været ville bli.', CAPTION, 'Sommerdagen, Sommernatt, Sommermål');\">Sommernatt</a>",
	gregoriantojd(4,16,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Magnus Erlendsson fra Orknøyene som ble kanonisert i 1135. I no. folketrad. ble dagen som oftest kalt tredje-dag sommer, og primstavmerket var en pil, øks eller et halvt kors, tolket som en hakke. Man skulle ofre av grøden denne dagen for å få et godt år.', CAPTION, 'Magnusmesse');\">Magnusmesse</a></a>",
	gregoriantojd(4,23,$year)=>"<a onClick=\"javascript:return overlib('Til minne om St. Georg som led martyrdøden under kristenforfølgelsene på begynnelsen av 300-tallet. I middelalderen skytshelgen for ridderne, i dag forbundet med soldater og speiderbevegelsen. I no. folketrad. var primstavmerket et kors eller en hest, da det ofte ble arrangert rytterturneringer denne dagen. Også vernehelgen for de spedalske. Navnet har blitt holdt levende gjennom tradisjonen rundt St. Jørgens hospital i Bergen.', CAPTION, 'Jørgensdag');\">Jørgensdag</a>",
	gregoriantojd(4,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om evangelisten Markus. I no. trad. ble dagen ofte kalt store gangdag, etter en kat. skikk med å gå i prosesjon rundt den dyrkede marken, bærende på løv, for å sikre avlingen. Primstavmerket var et blad på en kvist, en fjærpenn som symbol for evangelisten, eller en fugl, siden fuglene skulle ha to egg i redet denne dagen.', CAPTION, 'Marksumesse, Markusdagen');\">Markusmesse</a>",
	gregoriantojd(4,30,$year)=>"<a onClick=\"javascript:return overlib('For den eng. prinsesse Walburga. Feiringen av V. var lite utbredt i Norge, men hadde tradisjoner i Sør-Skandinavia og på Kontinentet. Dagen ble regnet som heksesabbat, og man beskyttet seg mot onde makter bl.a. ved å brenne bål denne natten.', CAPTION, 'Valborgsmesse');\">Valborgsmesse</a>",
	gregoriantojd(5,1,$year)=>"<a onClick=\"javascript:return overlib('Oftest 1. mai, men datoen varierte rundt i landet. I norsk folketradisjon het det at man kunne høre gjøken denne dagen, og den ville gi varsler avhengig av himmelretningen man hørte den fra. Primstavmerket var en gjøk eller et dobbelt kors til minne om apostlene Filip og Jacob. Dagen ble også kalt lille gangdag, fordi det enkelte steder var skikk å gå rundt åkrene for å skremme bort onde makter.', CAPTION, 'Gaukemesse');\">Gaukemesse</a>",
	gregoriantojd(5,3,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at Jesu kors ble gjenfunnet. I no. folketradisjon var primstavmerket et stort kors. I enkelte strøk av landet begynte man med såing og klipping av sauer, og nordlandsfiskerne satte kursen sydover til Bergen denne dagen.', CAPTION, 'Korsmesse vår');\">Korsmesse vår</a>",
	gregoriantojd(5,12,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for St. Pancras. I folketrad. ble det hevdet at denne helgenen kunne bringe frosten tilbake, derfor slapp man ikke buskapen på sommerbeite før etter denne dagen. Noen steder i landet har man hatt de samme tradisjoner som for gaukemesse denne dagen.', CAPTION, 'Gaukedagen <em>(av lat. Pancratii Martyris)</em>');\">Gaukedagen</a>",
	gregoriantojd(5,15,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Hallvard Vebjørnsson fra Lier som iflg. legenden ble drept i 1043 og senket i Drammensfjorden med en møllestein rundt halsen. I kat. tid var dette en viktig helligdag i Norge og på Island. Primstavmerket var en møllestein eller prikker (såkorn), da man var i den beste såtiden i Sør-Norge. Buskapen kunne også slippes ut. St. Hallvard ble dyrket først og fremst på Østlandet, og han er Oslo bys skytshelgen.', CAPTION, 'Hallvardsmesse, Hallvardsvaka, Hallsok');\">Hallvardsmesse</a>",
	gregoriantojd(5,18,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den sv. helgenkongen Erik Jedvardsson som ble drept 1160. Primstavmerket var et sverd, et aks eller en krone. Erik regnes som Sveriges skytshelgen.', CAPTION, 'Eriksmesse');\">Eriksmesse</a>",
	gregoriantojd(5,22,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var primstavmerket en bjørnefot; det het seg at bjørnen skulle komme ut av hiet sitt denne dagen.', CAPTION, 'Bjørnevåk');\">Bjørnevåk</a>",
	gregoriantojd(5,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om pave Urban I (222-230). Flere steder i Norge ble dagen regnet som begynnelsen på såtiden. Primstavmerket var et møkkagreip.', CAPTION, 'Urbanus');\">Urbanus</a>",
	gregoriantojd(6,3,$year)=>"<a onClick=\"javascript:return overlib('Til minne om biskop Erasmus fra Syria som ble drept under kristenforfølgelsene på 300-tallet. I no. folketrad. var primstavmerket et bor, antagelig et torturinstrument knytter til hans død. Dagen ble i Norge også kalt skoklefallsdagen, som siktet til at våronna skulle være ferdig slik at hestene kunne spennes fra skjekene (skoklene).', CAPTION, 'Rasmusdagen');\">Rasmusdagen</a>",
	gregoriantojd(6,8,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Medardus, biskop i Noyon, død 561. I no. folketrad. kunne primstavmerket være en fiskekrok, som skulle symbolisere innledningen til laksefisket.', CAPTION, 'Medardus og Gilardus');\">Medardus og Gilardus</a>",
	gregoriantojd(6,9,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den irske helgen Columba, som også ble dyrket på Vestlandet og på Island. Kolbjørn er en fornorsking av Columba. I no. folketrad. var primstavmerket en fisk. Denne dagen begynte sommeren, og laksen gikk opp i elvene.', CAPTION, 'Kolbjørn med laksen, Kolumbamesse');\">Kolumbamesse</a>",
	gregoriantojd(6,15,$year)=>"<a onClick=\"javascript:return overlib('For St. Vitus (Veit) fra Sicilia, som helbredet keiserens sønn for epilepsi. Skytshelgen for dem som lider av epilepsi, eller \'sanktveitsdans\'.', CAPTION, 'Vitusmesse');\">Vitusmesse</a>",
	gregoriantojd(6,17,$year)=>"<a onClick=\"javascript:return overlib('Til minne om St. Botolf, en av de største helgenene i den angelsaksiske kirken. I no. trad. var primstavmerket ofte et kors eller en bispestav. Lagtingsdag over hele landet fra middelalderen, ble enkelte steder regnet som helligdag helt til ca. 1850.', CAPTION, 'Botolfsmesse, Botsok');\">Botolfsmesse</a>",
	gregoriantojd(6,21,$year)=>"<a onClick=\"javascript:return overlib('I. no. folketrad. var primstavmerket en sol. Dagen har ellers flere av de samme tradisjonene som Vintersolverv, bl.a at man ikke skulle foreta seg arbeide der noe ble dreid rundt.', CAPTION, 'Sommersolhverv');\">Sommersolhverv</a>",
	gregoriantojd(6,22,$year)=>"<a onClick=\"javascript:return overlib('I kirkekalenderen var navnet De ti tusen martyrer, og dagen var viet flere helgener. I no. folketrad. var primstavmerket et timeglass. Dagen ble regnet som sommersolverv enkelte steder.', CAPTION, 'De ti tusen riddere');\">De ti tusen riddere</a>",
	gregoriantojd(6,23,$year)=>"<a onClick=\"javascript:return overlib('Kvelden er knyttet til den 24. juni og feires gjerne med bål og festligheter utover natten.', CAPTION, 'St.Hansaften');\">St.Hansaften</a>",
	gregoriantojd(6,24,$year)=>"<a onClick=\"javascript:return overlib('Til minne om døperen Johannes\' fødselsdag. I no. folketrad. var primstavmerket for denne dagen en sol eller et timeglass. Dagen ble betraktet som sommersolhverv, og var den viktigste merkedagen i sommerhalvåret. Tradisjonene rundt dagen er ofte mer folkelige enn kirkelige: de kretser om skaping og vern av liv, og kan ha sammmenheng med at feiringen ble knyttet opp mot det hedenske midtsommerblotet.', CAPTION, 'Jonsmesse, Jonsok, St. Hans');\">Jonsmesse</a>",
	gregoriantojd(6,9,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Peter og Paulus. I no. folketrad. har primstaven som oftest en nøkkel (Peters tegn), eller en blomst, da legende urter skulle samles denne dagen.', CAPTION, 'Petersmesse, Persok, Peter med gullnøkkelen');\">Petersmesse</a>",
	gregoriantojd(7,2,$year)=>"<a onClick=\"javascript:return overlib('Til minne om biskop Svithun av Winchester (død 862). I Stavanger bispedømme var primstavmerket gjerne en bispestav, da domkirken var vigd til ham. Ellers ble navneforvanskningen tolket som at man skulle syfte, dvs. luke bort ugress, fra åkeren denne dagen.', CAPTION, 'Syftesok');\">Syftesok</a>",
	gregoriantojd(7,8,$year)=>"<a onClick=\"javascript:return overlib('Til minne om St. Killian, en irsk misjonær som ble biskop i Würzburg. I no. folketrad. var primstavmerket en ljå, da det kunne være fare for at kornet ville tørke på denne tiden. Dagen faller sammen med Seljumesse til minne om om St. Sunniva som ble dyrket på Vestlandet, og som er Bergens skytshelgen. I Bjørgvin kunne primstavmerket være en krone.', CAPTION, 'Kjell fut, Kjell sviebygg, tredjevaka');\">Kjell fut</a>",
	gregoriantojd(7,10,$year)=>"<a onClick=\"javascript:return overlib('Til minne om da. kong Knud den hellige, død 1086. I no. folketrad. var primstavmerket en krone, rive eller ljå. Slåttonna skulle begynne rundt denne dagen.', CAPTION, 'Knutsok, Kong Knut, Knut med ljåen');\">Knutsok</a>",
	gregoriantojd(7,12,$year)=>"<a onClick=\"javascript:return overlib('Navnet på dagen hadde forbindelse med arbeidet i slåttonna.', CAPTION, 'Kari med riva');\">Kari med riva</a>",
	gregoriantojd(7,14,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. var primstavmerket ei sol. Tilsvarer 12. januar som midtvinterdag.', CAPTION, 'Midtsommerdag, gamle midtsommer');\">Midtsommerdag</a>",
	gregoriantojd(7,20,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Sta. Margareta fra Antiokia som ble drept under kristenforfølgelsene i 307. I no. folketrad. var primstavmerket oftest et hjul for å symbolisere dødsmåten hennes; dette ble muligens assosiert med en øse. Det kunne også være bokstaven M eller et kors med glorie. M. var den viktigste merkedagen for høstværet, og regn bragte ulykke.', CAPTION, 'Margretemesse, Marit vassause');\">Margretemesse</a>",
	gregoriantojd(7,22,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Maria Magdalena, som etter no. folketrad. var så skattet i himmelen at jomfru Maria tilbød henne et sete der. Primstavmerket var en krone med kors eller et beger.', CAPTION, 'Magdalimesse, Mari stol, Magdalidagen');\">Magdalimesse</a>",
	gregoriantojd(7,23,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. varer hundedagene til 23. eller 24. august. Navnet stammer kanskje fra grekernes tro på at Sirius, \'Hundestjernen\', var årsak til sommervarmen. På Østlandet kalles dagene ofte røtmånen eller røtnmånen (mulig av mty. rode, hund), og man mente at mat hadde lett for å råtne i hundedagene. Over hele landet het det at varmen kunne gjøre hundene gale.', CAPTION, 'Første hundedag');\">Første Hundedag</a>",
	gregoriantojd(7,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen Jakob, som ble halshogd i år 44. I no. folketrad. var primstavmerket et kors, et sverd eller en hatt. Trolig var hatten en pilegrimshatt, men ble tolket som regnværshatt. Regn på denne dagen ville gi en våt høst.', CAPTION, 'Jakobsmesse, Jakob våthatt');\">Jakobsmesse</a>",
	gregoriantojd(7,26,$year)=>"<a onClick=\"javascript:return overlib('For St. Anna, jomfru Marias mor. I no. folketrad. var ikke dagen avmerket på primstaven, men var kjent i forbindelse med værmerker. Regnet det denne dagen, ville det bli en våt høst.', CAPTION, 'Anna');\">Anna</a>",
	gregoriantojd(7,27,$year)=>"<a onClick=\"javascript:return overlib('For de syv kristne brødre fra Efesos som iflg. legenden ble forfulgt og innmuret i en hule. Der sovnet de og våknet 200 år senere. I no. folketradisjon het det at slik været var denne dagen ville det bli i syv uker fremover.', CAPTION, 'Syvsoverdagen');\">Syvsoverdagen</a>",
	gregoriantojd(7,29,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Olav Haraldsson som falt på Stiklestad 1030. I no. folketrad. var primstavmerket gjerne en øks; \'Olavsøks\' eller \'Olavsbile\'. Dagen ble feiret i Norge og på Færøyene lenge etter reformasjonen, bl.a. ved bålbrenning og ved å drikke \'St. Olafs skål\'. Var også en viktig merkedag for været; man kunne vente væromslag eller flom.', CAPTION, 'Olsok, Olafsvaka');\">Olsok</a>",
	gregoriantojd(8,1,$year)=>"<a onClick=\"javascript:return overlib('Katolsk minnedag for Peters fangenskap før martyriet. I no. folketradisjon var primstavmerket en nøkkel (St. Peters merke) eller lenker. Det skulle blåse mye denne dagen.', CAPTION, 'Peder vindfells dag, Peters lenker, Per vinkel');\">Peters vindfells dag</a>",
	gregoriantojd(8,3,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at Olav den hellige ble tatt opp av sandbakken ved Nidelva i 1031 og flyttet til Klemenskirken. I no. folketrad. var primstavmerket en øks, men mindre enn merket for olsok 29. juli.', CAPTION, 'Olsok Siare, Vesle olsok');\">Olsok Siare</a>",
	gregoriantojd(8,10,$year)=>"<a onClick=\"javascript:return overlib('Til minne om St. Laurentius, som i 258 ble lagt på en glødende rist for sin kristne tro. Han er skytshelgen bl.a for yrker som hadde forbindelse med ild og varme. I no. folketrad. er primstavmerket som oftest en rist. Dagen varslet været for vinteren, og slåttonna burde være ferdig.', CAPTION, 'Larsok, Lavransvaka');\">Larsok</a>",
	gregoriantojd(8,12,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for den hellige Klara fra Assisi (død 1253).', CAPTION, 'Klara');\">Klara</a>",
	gregoriantojd(8,15,$year)=>"<a onClick=\"javascript:return overlib('Til minne om jomfru Marias opptagelse til himmelen. I no. folketrad. var primstavmerket ofte en krone eller kvinnefigur.', CAPTION, 'Marias himmelfart, Marimesse førre, vår frue dyre');\">Marias himmelfart</a>",
	gregoriantojd(8,16,$year)=>"<a onClick=\"javascript:return overlib('For St. Rochus, som var skytshelgen for pestsyke og folk med smittsomme sykdommer. I no. folketrad. ble navnet assosiert med rug; denne dagen skulle vinterrugen i jorden.', CAPTION, 'Rugsok, Rugdagen');\">Rugsok</a>",
	gregoriantojd(8,23,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. het det noen steder at regn på denne dagen ville vare i fire uker.', CAPTION, 'Siste hundedag, Zakæus');\">Siste Hundedag</a>",
	gregoriantojd(8,24,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen Bartholomeus, som i iflg. tradisjonen ble levende flådd eller halshugget. Han er skytshelgen for fiskerne. Primstavtegnet var en øks, kniv eller et kors. Kniven ble tolket som at det var på tide å slakte bukkene. Dagen ble regnet som første høstdag, og man måtte passe seg for uvær som kunne gjøre skade på kornet.', CAPTION, 'Barsok, Bardonsok, Bertel brytestrå, Berdon bukkekniv');\">Barsok</a>",
	gregoriantojd(8,29,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at døperen Johannes ble halshugget. I no. folketrad. var primstavmerket gjerne et sverd (verge). Ingen måtte bære redskaper for hogst denne dagen.', CAPTION, 'Johannes halshogg, Vergismesse');\">Johannes halshogg</a>",
	gregoriantojd(8,31,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for St. Sunnivas skrin, som i 1170 ble flyttet fra Selje til Kristkirken i Bergen.', CAPTION, 'Sunniva');\">Sunniva</a>",
	gregoriantojd(9,1,$year)=>"<a onClick=\"javascript:return overlib('Til minne om St. Egidius (død 720). I no. folketrad. var han vernehelgen mot tørke, og man mente at pent vær denne dagen kunne føre til tørke og lite vann på kvernen. Primstavmerket var som oftest en kvernsten.', CAPTION, 'Kvernknarren, Eidismesse');\">Kvernknarren</a>",
	gregoriantojd(9,8,$year)=>"<a onClick=\"javascript:return overlib('Til minne om jomfru Marias fødselsdag. I no. folketrad. var primstavmerket ofte en krone, en \'M\' eller en sauesaks. Det var en god dag for klipping av sauene.', CAPTION, 'Morsmesse, Marimesse siare, Vår frue siare');\">Morsmesse</a>",
	gregoriantojd(9,12,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at en dråpe av Jesu blod i 1165 ble ført til Nidaros i en gullring (\'fingergull\'). Nordpå ble dette regnet som en god dag for klipping av sauene, og der ble dagen kalt saueklipperdagen.', CAPTION, 'Fingergullmesse');\">Fingergullmesse</a>",
	gregoriantojd(9,14,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at Jesu kors ble gjenerobret fra perserne i 629. I no. folketrad. var primstavmerket et kors. Dagen markerte at høsten begynte; kornet skulle være i hus og noen steder var dagen siste bufardag fra setrene.', CAPTION, 'Korsmesse om høsten');\">Korsmesse om høsten</a>",
	gregoriantojd(9,21,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen og evangelisten Mattheus som led martyrdøden i Persia. I no. folketrad. var primstavmerket ofte en øks, som ble satt i sammenheng med at lauvingen skulle begynne denne dagen.', CAPTION, 'Mattheusmesse, Mattismesse om høsten, Mattisdag');\">Mattheusmesse</a>",
	gregoriantojd(9,29,$year)=>"<a onClick=\"javascript:return overlib('Til minne om erkeengelen Mikael. Han ble regnet som hærføreren mot de onde maktene, og i no. folketrad. var primstavmerkene en lur som skulle vekke de døde, eller en vekt som sjelene skulle veies på. Det var en viktig fest- og merkedag, dagen for betaling av avgifter og flyttedag. All buskap og avling skulle være i hus.', CAPTION, 'Mikkelsmesse, Mikeli');\">Mikkelsmesse</a>",
	gregoriantojd(10,4,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Frans av Assisi (1182-1226) som grunnla Fransiscanerordenen. Flere klostre i Norge i middelalderen. I no. folketrad. var primstavmerket et halvkors, fordi dagen ikke ble betraktet som så hellig som dagene med helt kors. Godt vær denne dagen skulle gi godt vær hele måneden.', CAPTION, 'St. Frans');\">St. Frans</a>",
	gregoriantojd(10,7,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Birgitta fra Vadstena som ble kanonisert 1391. I nord. folketrad. var primstavmerket en bok eller et hus; begge henspeilet på klosteret i Vadstena. Dagen ble også kalt kåldagen, fordi vinterkålen nå skulle i hus.', CAPTION, 'Britemesse');\">Britemesse</a>",
	gregoriantojd(10,9,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den franske nasjonalhelgen Dionysius. Han var den føste biskop i Paris og led martyrdøden i 286. I no. folketrad. var primstavmerket en fisk, et flagg eller en bispestav. Man ventet sterk vind denne dagen, slik at løvet kunne blåse av trærne.', CAPTION, 'Dinesmesse, Deinets dag');\">Dinesmesse</a>",
	gregoriantojd(10,14,$year)=>"<a onClick=\"javascript:return overlib('Til minne om paven Calixtus som virket 217-222. I no. folketrad. ble primstaven snudd til vintersiden denne dagen, og merkene var et tre uten blader eller en hanske, sannsynligvis en pavehanske. Den ble senere til en vott som skulle symbolisere at vinteren kom, og dagen var en viktig merkedag for vinterværet over hele landet.', CAPTION, 'Vinternatt, Første vinternatt, -dag');\">Vinternatt</a>",
	gregoriantojd(10,18,$year)=>"<a onClick=\"javascript:return overlib('Til minne om evangelisten Lukas. I no. folketrad. var primstavmerket Lukas\' attributter, som var et kors, en okse eller en slaktebenk. Det ble tolket som en påminnelse om slaktetiden.', CAPTION, 'Lukasmesse');\">Lukasmesse</a>",
	gregoriantojd(10,21,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den hellge Ursula og de 11 000 jomfruene (tallet er antagelig feiltolket fra 11), som ble drept i 238 på vei fra pilegrimsferd i Roma. I no. folketrad. var primstavmerket gjerne en eller flere kvinnefigurer, en krone, pil, palme eller ring. Ringen ble tolket som forbud mot arbeidsoppgaver der noe ble dreid rundt denne dagen.', CAPTION, 'Ursula, 11 000 jomfruer');\">Ursula</a>",
	gregoriantojd(10,28,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen Simon som led martyrdøden i Persia. Han blir oftest nevnt sammen med Judas Taddeus, slik at dagen som oftest er viet til begge. I no. folketrad. var derfor primstavmerket et kors med to sett armer eller gren med to blader. Denne dagen var det skikk at folk i det første året de satte bo, reiste rundt i sognet og tigget et fat korn på hver gård.', CAPTION, 'Simonsmesse, Simon og Judas');\">Simonsmesse</a>",
	gregoriantojd(10,31,$year)=>"<a onClick=\"javascript:return overlib('Trolig var dette en keltisk høstfest, som ble spesielt dyrket i engelsktalende land (Halloween). Det var mange forestillinger om overnaturlige hendelser knyttet til denne natten. Den ble regnet som en farlig natt, og det var bl.a nødvendig å beskytte seg mot avdødes ånder. Det man hadde drømt, ville gå i oppfyllelse.', CAPTION, 'Allehelgensaften');\">Allehelgensaften</a>",
	gregoriantojd(11,1,$year)=>"<a onClick=\"javascript:return overlib('Minnedag for de helgener som ikke hadde fått sin egen dag. Innført av pave Gregor IV i det 9. årh. I no. folketrad. ble dagen ansett som en halv helligdag, og primstavmerket kunne være et kors eller skip (ofte omvendt) som symbol på kirken. Det omvendte skipet ble tolket som at ferdsel på sjøen skulle opphøre. Dagen var også en viktig merkedag for været.', CAPTION, 'Alle helgens dag, Helgemesse, Aldermesse');\">Alle helgens dag</a>",
	gregoriantojd(11,2,$year)=>"<a onClick=\"javascript:return overlib('I den katolske kirken til minne om sjelene som fortsatt er i skjærsilden. I no. trad. var dagen ofte ukjent, men noen ganger har den primstavmerke i form av en menneskefigur. Det het seg at man ikke skulle smelle i dørene denne dagen, for da ville en sjel kunne komme i klemme.', CAPTION, 'Alle sjelers dag');\">Alle sjelers dag</a>",
	gregoriantojd(11,11,$year)=>"<a onClick=\"javascript:return overlib('For Martin av Tours (død 397), som i følge legenden gjemte seg i en gåseflokk da han skulle velges til biskop. Han ble oppdaget da gjessene begynte å skrike, og påbød senere at alle gjess skulle slaktes. I no. folketrad. var primstavmerket ofte en gås eller en bispestav. Dagen har ikke hatt noen kirkelig trad. her i landet, men kan siden hedensk tid ha vært siste fest før julen. Man spiste gjerne svinekjøtt (\'mortensgås\' er en kontinental skikk), og delte maten med de fattige.', CAPTION, 'Mortensmesse, Mortensdag');\">Mortensmesse</a>",
	gregoriantojd(11,21,$year)=>"<a onClick=\"javascript:return overlib('Til minne om at den unge jomfru Maria ble framstilt i tempelet av sine foreldre. I no. trad. var primstavtegnet gjerne et hode med krone eller glorie.', CAPTION, 'Marioffer');\">Marioffer</a>",
	gregoriantojd(11,23,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Clemens 1., biskop i Roma 92—101. Han ble sendt til Krim på straffearbeid. Etter å ha bygget kirker der, ble han bundet til et anker og druknet i Svartehavet. Han var sjøfolkenes skytshelgen. I no. folketrad. var primstavmerket gjerne et anker, en kirke eller en pavekrone. Ankeret ble tolket som at ferdsel på sjøen skulle opphøre for året. Navnet Klemet ble assosiert med at man skulle \'klemme\' (knipe inn) i kosten før jul.', CAPTION, 'Klemetsmesse, Klemet kirkebygger/saueskjærer, Båtsok');\">Klemetsmesse</a>",
	gregoriantojd(11,25,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Catharina fra Alexandria som i 313 ble lagt på et hjul med pigger og senere halshogd. I no. folketrad. var primstavmerket ofte et sverd, et kors eller et hjul. Hjulet ble tolket som en rokk; det het seg at spinnetiden skulle ta til denne dagen.', CAPTION, 'Karimesse, Karenmesse, Kari med rokken');\">Karimesse</a>",
	gregoriantojd(11,30,$year)=>"<a onClick=\"javascript:return overlib('Til minne om fiskeren og apostelen Andreas, som ble naglet til et X-formet kors (\'andreaskors\'). I no. folketrad. var primstavmerket et slikt kors, eller en fiskekrok. Dette ble tatt som tegn på at julefisket skulle begynne. Korset ble også tolket som en revesaks, derfor skulle man sette ut revefellene denne dagen.', CAPTION, 'Andreasmesse, Anders fisker');\">Andreasmesse</a>",
	gregoriantojd(12,4,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Barbara fra Nikomedia som iflg. legenden ble stengt inne i et tårn eller hule av sin hedenske far og led martyrdøden år 306. I no. folketrad. var primstavmerket et kors, et tårn et sverd eller en\'B\'. Denne dagen skulle solen forsvinne og komme tilbake til Lussinatt 13. des.', CAPTION, 'Barbromesse');\">Barbromesse</a>",
	gregoriantojd(12,6,$year)=>"<a onClick=\"javascript:return overlib('Til minne om biskop Nicolaus fra Lilleasia, død ca. år 350. Det er mange legender om ham; bl.a skal han ha hjulpet en fattig mann med gaver slik at han kunne ha døtrene sine hos seg. Herfra stammer kanskje skikken med å gi gaver på denne kvelden; den har blitt flyttet til 24.-25. des. i Norden og engelsktalende land, men holdes fortsatt i hevd i enkelte land på Kontinentet. I no. folketrad. var primstavmerket ofte en bispelue, bispestav eller en \'N\'.', CAPTION, 'Nilsmesse, Nikolausdagen');\">Nilsmesse</a>",
	gregoriantojd(12,8,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Marias unnfangelse uten arvesynd. I no. folketrad. viser primstaven et kronet hode eller en bok. Dagen ble også kalt vår frue ventedør, da Maria ventet Kristi fødsel denne dagen. Gravide kunne be til henne denne dagen for å unngå å føde for sent.', CAPTION, 'Maria unnfangelsesdag');\">Maria unnfangelsesdag</a>",
	gregoriantojd(12,9,$year)=>"<a onClick=\"javascript:return overlib('Til minne om jomfru Marias mor. I no. folketrad. var primstavmerket et kvinnehode. Denne dagen var det enkelte steder skikk å begynne bryggingen av juleølet, og i Seljord skulle klesvasken til jul begynne.', CAPTION, 'Anna matris Mariae, Anna røytrauv, Pissihose');\">Anna matris Mariae</a>",
	gregoriantojd(12,10,$year)=>"<a onClick=\"javascript:return overlib('For heltinnen i Judiths bok. I no. folketrad. het det flere steder at man skulle tilberede malt til juleølet.', CAPTION, 'Judith');\">Judith</a>",
	gregoriantojd(12,13,$year)=>"<a onClick=\"javascript:return overlib('Til minne om Lucia fra Syrakus, som led martyrdøden under kristenforfølgelsene i 304. I Norden ble feiringen av l. vanlig først etter reformasjonen, og i folketrad. ble hun ble oppfattet som en del av mørkemaktene, trolig på grunn av navnelikheten med Lucifer. Dagen var noen steder avmerket på primstaven, enten som et bål; hun ble forsøkt brent på bålet, eller som et lys, som henspeiler på betydningen av navnet. Julen tok til denne dagen, og det meste av grovarbeidet skulle være gjort.', CAPTION, 'Luciadagen, Lussimesse, Lussinatt');\">Luciadagen</a>",
	gregoriantojd(12,17,$year)=>"<a onClick=\"javascript:return overlib('For Lasarus, som Jesus vekket opp av graven. Han ble betraktet som dødens overvinner, og ble skytshelgen for de syke. I no. folketrad. fikk de gamle og syke spesiell forpleining denne dagen.', CAPTION, 'Lasarusdagen');\">Lasarusdagen</a>",
	gregoriantojd(12,21,$year)=>"<a onClick=\"javascript:return overlib('Til minne om apostelen Thomas. I no. folketrad. var primstavmerket en tønne, et kors eller en hånd som symbol på den \'vantro Thomas\'. Over hele landet var det tradisjon for at juleølet skulle brygges denne dagen. Man ventet også mildvær, eller \'kakelinna\'.', CAPTION, 'Tomasmesse I, Tomas brygger');\">Tomasmesse I</a>",
	gregoriantojd(12,22,$year)=>"<a onClick=\"javascript:return overlib('I no. folketrad. hadde primstavmerket en sol. Denne dagen skulle man ikke foreta seg arbeide der noe ble dreid rundt. Heller ikke skulle man ikke bake, da kakene ikke ville feste seg på takkene, og juleølet skulle være ferdig så ikke \'solhvervet\' kom i.', CAPTION, 'Vintersolhverv');\">Vintersolverv</a>",
	gregoriantojd(12,23,$year)=>"<a onClick=\"javascript:return overlib('Til minne om den isl. biskop Şórlákr Şórhalsson (1133-1193), som ble godtatt som helgen i 1198. Her i landet ble han dyrket på Vestlandet og i Nord-Norge, og på primstavene kan man finne dagen avmerket som et halvkors. Nordafjells kalles dagen også sjursmesse.', CAPTION, 'Tollesmesse, Lille julaften');\">Tollesmesse</a>",
	gregoriantojd(12,24,$year)=>"<a onClick=\"javascript:return overlib('Dagen er vanligv&nbsp;is ikke avmerket på norske primstaver, siden feiringen av julen tradisjonelt var knyttet til julenatten eller første juledag. Feiringen har røtter i hedensk skikk, der julen var en fest rundt vintersolhverv for å ønske solen velkommen tilbake igjen.', CAPTION, 'Julaften');\">Julaften</a>",
	gregoriantojd(12,25,$year)=>"<a onClick=\"javascript:return overlib('I no. trad. ble dagen regnet som den viktigste merkedagen i året, og primstaven kunne være merket med drikkehorn, kandelaber, sol eller tønne. Julenatten kunne man få varsler både om fiske, avling, kjærlighet og liv og død. Det ble oppfattet som uoppdragent å gå på besøk denne dagen; i Nord-Norge ble en slik besøkende kalt \'Juledags-Petter\'.', CAPTION, '1. Juledag');\">1. Juledag</a>",
	gregoriantojd(12,26,$year)=>"<a onClick=\"javascript:return overlib('For martyren Stefanus, som iflg. legenden var stallgutt hos Herodes, og derfor ble regnet som hestenes skytshelgen. I hedensk tid het det at man kunne man jage vekk onde makter med bråk og larm denne dagen. I hele Norden var det vanlig med kappritt mellom unge menn, og hestene skulle løpe seg svette for å beskytte rytteren mot sykdom.', CAPTION, 'Staffansmesse, Stefansdag');\">Staffansmesse, Stefansdag</a>",
	gregoriantojd(12,28,$year)=>"<a onClick=\"javascript:return overlib('Til minne om barna som Herodes lot drepe i Betlehem for å komme Jesubarnet til livs. I no. folketrad. var primstavmerket et lite kors. Denne dagen skulle barna holde fest; gå på besøk til hverandre og ha det moro på de voksnes bekostning. Slik været var denne dagen, ville det bli kommende sommer.', CAPTION, 'Barnedag');\">Barnedag</a>",
	gregoriantojd(12,29,$year)=>"<a onClick=\"javascript:return overlib('For erkebiskop Thomas Beckett, som ble myrdet 1170 i Canterbury. I no. folketrad. het det at dagen varslet været for de kommende fem ukene.', CAPTION, 'Tomasmesse II, Femtedag jul');\">Tomasmesse II</a>",
	gregoriantojd(12,31,$year)=>"<a onClick=\"javascript:return overlib('Etter dødsdagen til St. Silvester I. Dagen er ikke avmerket på norske primstaver. Det var likevel knyttet forestillinger til at det var en farlig dag, der det meste av det man foretok seg ville mislykkes.', CAPTION, 'Silvesteraften');\">Silvesteraften</a>"
);
?>